export { default as PostComment } from './PostComment/component'
export { default as Header } from './Header/component'
export { default as NewPost } from './NewPost/component'
export { default as Post } from './Post/component'
export { default as SideBar } from './SideBar/component'